- name: create base directory
  file: path=~/git/redmine recurse=yes state=directory
- name:
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    curl -sSL https://get.rvm.io | bash -s stable

# vim: set ts=2 sw=2 et:
