- name: download plugins (git)
  git: repo={{ item.url }} dest={{ redmine_home }}/plugins/{{ item.name }} version={{ item.rev }}
  with_items:
    - { name: advanced_roadmap_v2, url: "https://github.com/Coren/redmine_advanced_roadmap_v2.git", rev: master }
    - { name: clipboard_image_paste, url: "https://github.com/peclik/clipboard_image_paste.git", rev: master }
    - { name: redmine_absolute_dates, url: "https://github.com/suer/redmine_absolute_dates.git", rev: master }
    - { name: redmine_banner, url: "https://github.com/akiko-pusu/redmine_banner.git", rev: master }
    - { name: redmine_custom_workflows, url: "https://github.com/anteo/redmine_custom_workflows.git", rev: master }
    - { name: redmine_default_assign, url: "https://github.com/giddie/redmine_default_assign.git", rev: master }
    - { name: redmine_default_due_date, url: "https://github.com/basyura/redmine_default_due_date.git", rev: master }
    - { name: redmine_default_version, url: "https://github.com/benasher44/redmine_default_version.git", rev: master }
    - { name: redmine_dmsf, url: "https://github.com/danmunn/redmine_dmsf.git", rev: "v1.5.5" }
    - { name: redmine_importer, url: "https://github.com/zh/redmine_importer.git", rev: master }
    - { name: redmine_local_avatars, url: "https://github.com/ncoders/redmine_local_avatars.git", rev: master }
    - { name: sidebar_hide, url: "https://github.com/bdemirkir/sidebar_hide.git", rev: master }
    - { name: view_customize, url: "https://github.com/onozaty/redmine-view-customize.git", rev: master }

- name: download plugins (hg)
  hg: repo={{item.url}} dest={{redmine_home}}/plugins/{{item.name}} revision={{item.rev}}
  with_items:
    - { name: redmine_code_review, url: "https://bitbucket.org/haru_iida/redmine_code_review", rev: default }
    - { name: redmine_issue_templates, url: "https://bitbucket.org/akiko_pusu/redmine_issue_templates", rev: default }
    - { name: redmine_theme_changer, url: "https://bitbucket.org/haru_iida/redmine_theme_changer", rev: default }
    - { name: redmine_wiki_extensions, url: "https://bitbucket.org/haru_iida/redmine_wiki_extensions", rev: default }
    - { name: redmine_work_time, url: "https://bitbucket.org/tkusukawa/redmine_work_time", rev: default }

- name: install plugins
  shell: bundle install --local path=vendor/bundle --without production chdir={{ redmine_home }}

- name: migration for plugins
  shell: rake redmine:plugins:migrate chdir={{ redmine_home }}
